x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    releaseTypes:
      - Feature
    recommended: false

  clusterConstraints:
    resources:
      - replicas: 1
        requests:
          cpu: 100m
          memory: 100Mi

  images:
    '':
      properties:
        hydra.image.repo:
          type: REPO_WITH_REGISTRY
        hydra.image.tag:
          type: TAG
    postgresql:
      properties:
        postgresql.image:
          type: FULL
    postgresql-exporter:
      properties:
        postgresql.exporter.image:
          type: FULL
    prometheus-to-sd:
      properties:
        metrics.image:
          type: FULL

  deployerServiceAccount:
    description: Creates app resources, including Webhooks and ClusterRoleBindings.
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups:
            - 'rbac.authorization.k8s.io'
            resources:
            - 'clusterroles'
            - 'clusterrolebindings'
            verbs:
            - '*'
          - apiGroups:
            - ''
            resources:
            - 'namespaces'
            verbs:
            - 'create'
            - 'list'
            - 'update'
            - 'patch'

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  postgresql.persistence.size:
    type: string
    title: PostgreSQL storage size
    description: Storage size for PostgreSQL persistent volume
    default: '8Gi'
    pattern: '^[1-9][0-9]*(\.[0-9]+)?[TGM]i?$'
  metrics.exporter.enabled:
    type: boolean
    title: Enable Stackdriver Metrics Exporter
    description: Your GCP project should have Stackdriver enabled. For non-GCP clusters, export of metrics to Stackdriver is not supported yet
    default: false

  # Generated values
  postgresql.password:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32

required:
- name
- namespace
- metrics.exporter.enabled