## Configuration values for the PostgreSQL server.
postgresql:
  image: gcr.io/cloud-marketplace/google/postgresql13:13.4

  exporter:
    image: gcr.io/cloud-marketplace/google/postgresql-exporter0:0.8.0

  cpu: 1000m
  memory: 1Gi

  user: hydra
  password: null
  postgresDatabase: hydra

  persistence:
    size: 8Gi


metrics:
  image: null
  exporter:
    enabled: false

deployer:
  image: null

# -- Configure ingress
ingress:
  public:
    enabled: true

  admin:
    enabled: true

# -- Configure ORY Hydra itself
hydra:
  image:
    # -- ORY Hydra image
    repo: gcr.io/ccm-ops-test-adhoc
    # -- ORY Hydra version
    tag: 1.11.8
  serviceAccount:
    name: hydra-sa
  # -- The ORY Hydra configuration. For a full list of available settings, check:
  #  https://www.ory.sh/docs/hydra/reference/configuration

  dangerousForceHttp: true
  # -- Configure HPA - MAKE IT OPTIONAL, FOR USER TO CHOOSE
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3

# -- Configures the Kubernetes service
service:
  # -- Configures the Kubernetes service for the proxy port.
  public:
    # -- En-/disable the service
    enabled: true
    # -- The service type
    type: ClusterIP

  admin:
    # -- En-/disable the service
    enabled: true
    # -- The service type
    type: ClusterIP

# -- Values for initialization job
job:
  serviceAccount:
    name: "hydra-migration-sa"


# -- Configures controller setup
maester:
  enabled: true
