apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-public
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 1
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /health/ready
    port: 4444
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Release.Name }}-admin
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 1
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /health/ready
    port: 4445
  