{{- if .Values.ingress.admin.enabled -}}
{{- $fullName := include "hydra.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hydra.labels" . | nindent 4 }}
spec:
  ingressClassName: ""
  {{- if .Values.ingress.admin.tls }}
  tls:
    {{- range .Values.ingress.admin.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.admin.hosts }}
    - host: "admin.hydra.localhost"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-admin
                port:
                  name: http
              {{- else }}
              serviceName: {{ $fullName }}-admin
              servicePort: http
              {{- end }}
              {{- end }}
{{- end }}
