{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-public
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hydra.labels" . | nindent 4 }}
spec:
  rules:
    - host: "public.hydra.localhost"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ .Release.Name }}-public
                port:
                  name: http
              {{- else }}
              serviceName: {{ .Release.Name }}-public
              servicePort: http
              {{- end }}

