---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.job.serviceAccount.name }}
  labels:
    {{- include "hydra.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook: "post-install, post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
