apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hydra.secretname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hydra.labels" . | indent 4 }}
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/resource-policy: "keep"
type: Opaque
data:
  # Generate a random secret if the user doesn't give one. User given password has priority
  secretsSystem: {{ randAlphaNum 32 | b64enc | quote }}
  secretsCookie: {{ randAlphaNum 32 | b64enc | quote }}
  dsn: {{ include "hydra.dsn" . | b64enc | quote }}

